---
abstract: 'Encoding and decoding of C<application/x-www-form-urlencoded> encoding.'
author:
  - 'Christian Hansen C<chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URL-Encode
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Exporter: 0
  XSLoader: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chansen/p5-url-encode
version: 0.02
